version: '3.1'

services:
  flask-app:
    build: .
    container_name: Passerelle_Deltic_flask
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app:create_app
      - FLASK_ENV=development
      - OAUTHLIB_INSECURE_TRANSPORT=1
    networks:
      - monitoring
    restart: always

networks:
  monitoring:
