version: '3.1'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app:create_app
      - FLASK_ENV=development
      - OAUTHLIB_INSECURE_TRANSPORT=1
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - flask-app
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - monitoring

volumes:
  grafana-storage:

networks:
  monitoring:
