json = {
    "Result": 0,
    "User": {
        "User_Id": "2199661efe186f32a741b9b286070b3f",
        "FirstName": "Marius",
        "LastName": "Hivelin",
        "Mail": "marius.hivelin@gmail.com",
        "Department": "DELTIC - Technique",
        "Mail_Sur_Depot": None,
        "Derniere_Connexion": "2024-06-24 17:23:44",
        "compte_technique": "0",
        "Prefs": {
            "lang": "fr",
            "Nb_Par_Page": 20,
            "N_Comments_Color": "1",
            "Comments_Color": "FAF898",
            "TimeZone": "Europe/Paris",
            "coll_21_Hidden_Result_Indexes": "|custom_f1|custom_f3|custom_f2|custom_t6|custom_t7|custom_n6|custom_n4|custom_n1|custom_n5|custom_t5|custom_n2|custom_t4|custom_t1|Res_Id|Creation_Date|N_Status|PDF_Filesize|Original_Filesize|Comment|Stamp|Postit|Conversation|N_Modele_LAD|signed|Statut_Signature|Doublons|Doublons_Inactifs|Filename|Format|Upload_User_Id|signataires_oodrive|signataires_oodrive_signed|signataires_oodrive_waiting|signataires_oodrive_refused|folders|notified_conversations|follow_notified_conversations|Shipment_Status|Posted|History|Thumb|Linked_Docs|Docs_Doublons|",
            "_Hidden_Result_Indexes": "|Res_Id|Collection|Creation_Date|N_Status|PDF_Filesize|Original_Filesize|Comment|Stamp|Postit|Conversation|N_Modele_LAD|signed|Statut_Signature|Filename|Format|Upload_User_Id|signataires_oodrive|signataires_oodrive_signed|signataires_oodrive_waiting|signataires_oodrive_refused|folders|notified_conversations|follow_notified_conversations|Shipment_Status|Posted|Thumb|Linked_Docs|",
            "coll_21_Result_Indexes": "|custom_n3|custom_t2|custom_t3|custom_d4|custom_d1|Commented|Page_Count|",
            "_Result_Indexes": "|Res_Id|N_Status|Filesize|FilesizeOriginal|Comment|Stamp|N_Modele_LAD|Postit|signed|Statut_Signature|Format|folders|Linked_Docs|Shipment_Status|Is_Commented|Comment|Thumb|History|",
            "coll_23_Hidden_Result_Indexes": "|custom_f1|custom_f3|custom_f2|custom_t6|custom_t7|custom_n6|custom_n4|custom_n1|custom_n5|custom_t5|custom_n2|custom_t4|custom_t1|Res_Id|Creation_Date|N_Status|PDF_Filesize|Original_Filesize|Comment|Stamp|Postit|Conversation|N_Modele_LAD|signed|Statut_Signature|Doublons|Doublons_Inactifs|Filename|Format|Upload_User_Id|signataires_oodrive|signataires_oodrive_signed|signataires_oodrive_waiting|signataires_oodrive_refused|folders|notified_conversations|follow_notified_conversations|Shipment_Status|Posted|History|Thumb|Linked_Docs|Docs_Doublons|",
            "coll_23_Result_Indexes": "|custom_n3|custom_t2|custom_t3|custom_d4|custom_d1|Commented|Page_Count|",
            "coll_11_Hidden_Result_Indexes": "|custom_t8|custom_d4|custom_d1|custom_f1|custom_f3|custom_f2|custom_t6|custom_n6|custom_n4|custom_n1|custom_n5|custom_t5|custom_n2|custom_t4|custom_t1|custom_t7|custom_n8|custom_n9|custom_d2|Res_Id|Creation_Date|N_Status|PDF_Filesize|Original_Filesize|Comment|Stamp|Postit|Conversation|N_Modele_LAD|signed|Statut_Signature|Filename|Format|Upload_User_Id|signataires_oodrive|signataires_oodrive_signed|signataires_oodrive_waiting|signataires_oodrive_refused|folders|notified_conversations|follow_notified_conversations|Shipment_Status|Posted|History|Thumb|Linked_Docs|",
            "coll_11_Result_Indexes": "|custom_n10|custom_n3|custom_n7|custom_t2|custom_t3|Commented|Page_Count|",
            "Upload_Form": "FLASH",
        },
        "Est_SuperAdmin": False,
        "Last_Page": "/data/GedH/www/deltic_demo/ws/3_0/Zeendoc.php",
        "Last_Access": "2024-06-25 09:23:03",
    },
    "Client": {
        "Status": [
            {"Id": 2, "Label": "TO BE INDEXED"},
            {"Id": 1, "Label": "INDEXED"},
            {"Id": -1, "Label": "DELETED"},
        ],
        "Collections_Ordonnees": ["coll_21", "coll_23"],
    },
    "Collections": [
        {
            "Coll_Id": "coll_21",
            "Label": "Classeur Fournisseur | Marius",
            "Indexes": [],
            "Index": [
                {
                    "Index_Id": "custom_n3",
                    "Label": "Informations Générales|Type de document",
                    "Mandatory": True,
                    "Is_ListChoice": 1,
                    "Is_Date": 0,
                    "Is_Numeric": 1,
                    "Is_Autocomplete": 0,
                    "Is_Multivalued": 0,
                    "Type": "DOCUMENT_TYPE",
                    "Possible_Value": [
                        {"Id": 13, "Label": "Avoir"},
                        {"Id": 15, "Label": "Bon de commande"},
                        {"Id": 14, "Label": "Bon de livraison"},
                        {"Id": 16, "Label": "Devis"},
                        {"Id": 3, "Label": "Facture"},
                    ],
                },
                {
                    "Index_Id": "custom_t2",
                    "Label": "Informations Générales|Fournisseur",
                    "Mandatory": True,
                    "Is_ListChoice": 0,
                    "Is_Date": 0,
                    "Is_Numeric": 0,
                    "Is_Autocomplete": 1,
                    "Is_Multivalued": 0,
                    "Type": "DESIGNATION_FOURNISSEUR_CHORUS_PRO",
                },
                {
                    "Index_Id": "custom_t3",
                    "Label": "Informations Générales|Référence du document",
                    "Mandatory": True,
                    "Is_ListChoice": 0,
                    "Is_Date": 0,
                    "Is_Numeric": 0,
                    "Is_Autocomplete": 0,
                    "Is_Multivalued": 0,
                    "Type": "NUMERO_FACTURE_CHORUS_PRO",
                },
                {
                    "Index_Id": "custom_d4",
                    "Label": "Informations Générales|Date du document",
                    "Mandatory": True,
                    "Is_ListChoice": 0,
                    "Is_Date": 1,
                    "Is_Numeric": 0,
                    "Is_Autocomplete": 0,
                    "Is_Multivalued": 0,
                    "Type": "DATE_FACTURE_CHORUS_PRO",
                },
                {
                    "Index_Id": "custom_d1",
                    "Label": "Informations Générales|Date d'échéance",
                    "Mandatory": False,
                    "Is_ListChoice": 0,
                    "Is_Date": 1,
                    "Is_Numeric": 0,
                    "Is_Autocomplete": 0,
                    "Is_Multivalued": 0,
                    "Type": "DATE_ECHEANCE",
                },
                {
                    "Index_Id": "custom_f1",
                    "Label": "Informations Générales|Montant HT",
                    "Mandatory": False,
                    "Is_ListChoice": 0,
                    "Is_Date": 0,
                    "Is_Numeric": 1,
                    "Is_Autocomplete": 0,
                    "Is_Multivalued": 0,
                    "Type": "HT",
                },
                {
                    "Index_Id": "custom_f3",
                    "Label": "Informations Générales|Montant TVA",
                    "Mandatory": False,
                    "Is_ListChoice": 0,
                    "Is_Date": 0,
                    "Is_Numeric": 1,
                    "Is_Autocomplete": 0,
                    "Is_Multivalued": 0,
                    "Type": "TVA",
                },
                {
                    "Index_Id": "custom_f2",
                    "Label": "Informations Générales|Montant TTC",
                    "Mandatory": False,
                    "Is_ListChoice": 0,
                    "Is_Date": 0,
                    "Is_Numeric": 1,
                    "Is_Autocomplete": 0,
                    "Is_Multivalued": 0,
                    "Type": "TTC",
                },
                {
                    "Index_Id": "custom_t6",
                    "Label": "Validation|Responsable de validation",
                    "Mandatory": False,
                    "Is_ListChoice": 1,
                    "Is_Date": 0,
                    "Is_Numeric": 0,
                    "Is_Autocomplete": 0,
                    "Is_Multivalued": 0,
                    "Type": "USERS_LIST",
                    "Possible_Value": [
                        {
                            "Id": "74f916c011391ba7ed47caf1e1ce083c",
                            "Label": "GRENOUILLEAU Antonin",
                        },
                        {
                            "Id": "2199661efe186f32a741b9b286070b3f",
                            "Label": "Hivelin Marius",
                        },
                        {
                            "Id": "ef8d29f5361c2b7c12a25511436bbc02",
                            "Label": "JOLLYS Mickaël",
                        },
                    ],
                },
                {
                    "Index_Id": "custom_t7",
                    "Label": "Validation|Responsable de validation BAP",
                    "Mandatory": False,
                    "Is_ListChoice": 1,
                    "Is_Date": 0,
                    "Is_Numeric": 0,
                    "Is_Autocomplete": 0,
                    "Is_Multivalued": 0,
                    "Type": "USERS_LIST",
                    "Possible_Value": [
                        {
                            "Id": "3e9ad4345be1b5f6e721d06d7729d39d",
                            "Label": "Alexandre BAUDON",
                        },
                        {
                            "Id": "74f916c011391ba7ed47caf1e1ce083c",
                            "Label": "Antonin GRENOUILLEAU",
                        },
                        {
                            "Id": "3a04a02e0a0f419b241ffc12e65028fa",
                            "Label": "Arnaud DELASTRE",
                        },
                        {
                            "Id": "a1c7a2fc949869d9bd625ac099e7bd9c",
                            "Label": "Audrey MAS",
                        },
                        {
                            "Id": "e2afc39b8813fc3c4f30a2dccec1adf3",
                            "Label": "Fleur CIANTELLI",
                        },
                        {
                            "Id": "710bca52a37973418e783f7fefde58f5",
                            "Label": "Formulaire Jotform",
                        },
                        {
                            "Id": "e88bef785b5a8c9c8ce8212ea94c2226",
                            "Label": "Germain MALICZAK",
                        },
                        {
                            "Id": "e69645dbaa97bcbb9e5fa62246eddd7c",
                            "Label": "Guillaume GRIMAUD",
                        },
                        {
                            "Id": "b629639e175bc740e092f0923de5e5ab",
                            "Label": "Julien CASTAING",
                        },
                        {
                            "Id": "182a9f1ff961e5acffc5dc52636734ad",
                            "Label": "Ludovic TONDU",
                        },
                        {
                            "Id": "2199661efe186f32a741b9b286070b3f",
                            "Label": "Marius Hivelin",
                        },
                        {
                            "Id": "a2f35187c8bb508f1f2fd002ac2c5282",
                            "Label": "Marius Hivelin",
                        },
                        {
                            "Id": "ef8d29f5361c2b7c12a25511436bbc02",
                            "Label": "Mickaël JOLLYS",
                        },
                        {
                            "Id": "76cc5e409d20c8e7667f902fb9a13eaa",
                            "Label": "Nicolas SCAGLIOLA",
                        },
                        {
                            "Id": "a0f2166611fa922b2e9698c6b3ab7c9e",
                            "Label": "Oscar WOLLMANN",
                        },
                        {
                            "Id": "df9e0cf700d9e6d8fb2a883ca164c5f1",
                            "Label": "Recette Z+ DELTIC DEMO",
                        },
                    ],
                },
                {
                    "Index_Id": "custom_n6",
                    "Label": "Comptabilité|Code journal",
                    "Mandatory": False,
                    "Is_ListChoice": 1,
                    "Is_Date": 0,
                    "Is_Numeric": 1,
                    "Is_Autocomplete": 0,
                    "Is_Multivalued": 0,
                    "Type": "FOREIGN_TABLE",
                    "Possible_Value": [{"Id": 1, "Label": "AC - Achats"}],
                },
                {
                    "Index_Id": "custom_n4",
                    "Label": "Comptabilité|Compte Fournisseur",
                    "Mandatory": False,
                    "Is_ListChoice": 1,
                    "Is_Date": 0,
                    "Is_Numeric": 1,
                    "Is_Autocomplete": 0,
                    "Is_Multivalued": 0,
                    "Type": "FOREIGN_TABLE",
                    "Possible_Value": [
                        {"Id": 9, "Label": "401FOURN - NOM DU FOURNISSEUR"}
                    ],
                },
                {
                    "Index_Id": "custom_n1",
                    "Label": "Comptabilité|Imputation HT",
                    "Mandatory": False,
                    "Is_ListChoice": 1,
                    "Is_Date": 0,
                    "Is_Numeric": 1,
                    "Is_Autocomplete": 0,
                    "Is_Multivalued": 1,
                    "Type": "VENTILATION_HT",
                    "Possible_Value_CreditDebit": [
                        {"Nom_Groupe": "CREDIT", "Id_Father": 1},
                        {
                            "Nom_Groupe": "DEBIT",
                            "Id_Father": -1,
                            "Membre_Groupe": [
                                {"Id": 650, "Label": "6251000 - COMPTE DE TEST"}
                            ],
                        },
                    ],
                    "Is_Son": 1,
                    "Father": "",
                    "Possible_Value": [
                        {
                            "Nom_Groupe": "-1",
                            "Id_Father": -1,
                            "Membre_Groupe": [
                                {"Id": 650, "Label": "6251000 - COMPTE DE TEST"}
                            ],
                        }
                    ],
                },
                {
                    "Index_Id": "custom_n5",
                    "Label": "Comptabilité|Imputation TVA",
                    "Mandatory": False,
                    "Is_ListChoice": 1,
                    "Is_Date": 0,
                    "Is_Numeric": 1,
                    "Is_Autocomplete": 0,
                    "Is_Multivalued": 1,
                    "Type": "VENTILATION_TVA",
                    "Possible_Value_CreditDebit": [
                        {"Nom_Groupe": "CREDIT", "Id_Father": 1},
                        {
                            "Nom_Groupe": "DEBIT",
                            "Id_Father": -1,
                            "Membre_Groupe": [
                                {"Id": 17, "Label": "44560000 - COMPTE DE TEST"}
                            ],
                        },
                    ],
                    "Is_Son": 1,
                    "Father": "",
                    "Possible_Value": [
                        {
                            "Nom_Groupe": "-1",
                            "Id_Father": -1,
                            "Membre_Groupe": [
                                {"Id": 17, "Label": "44560000 - COMPTE DE TEST"}
                            ],
                        }
                    ],
                },
                {
                    "Index_Id": "custom_t5",
                    "Label": "Comptabilité|Complément libellé",
                    "Mandatory": False,
                    "Is_ListChoice": 0,
                    "Is_Date": 0,
                    "Is_Numeric": 0,
                    "Is_Autocomplete": 0,
                    "Is_Multivalued": 0,
                    "Type": "TEXT",
                },
                {
                    "Index_Id": "custom_n2",
                    "Label": "Comptabilité|Mode de règlement",
                    "Mandatory": False,
                    "Is_ListChoice": 1,
                    "Is_Date": 0,
                    "Is_Numeric": 1,
                    "Is_Autocomplete": 0,
                    "Is_Multivalued": 0,
                    "Type": "FOREIGN_TABLE",
                    "Possible_Value": [
                        {"Id": 1, "Label": "CB - Carte Bleue"},
                        {"Id": 3, "Label": "CHQ - Chèque"},
                        {"Id": 2, "Label": "VIR - Virement"},
                    ],
                },
                {
                    "Index_Id": "custom_t4",
                    "Label": "Comptabilité|Numéro de pièce comptable (auto)",
                    "Mandatory": False,
                    "Is_ListChoice": 0,
                    "Is_Date": 0,
                    "Is_Numeric": 0,
                    "Is_Autocomplete": 0,
                    "Is_Multivalued": 0,
                    "Type": "TEXT",
                },
                {
                    "Index_Id": "custom_t1",
                    "Label": "Comptabilité|Exporté (auto)",
                    "Mandatory": False,
                    "Is_ListChoice": 0,
                    "Is_Date": 0,
                    "Is_Numeric": 0,
                    "Is_Autocomplete": 0,
                    "Is_Multivalued": 0,
                    "Type": "TEXT",
                },
                {
                    "Index_Id": "custom_n7",
                    "Label": "BAP",
                    "Mandatory": False,
                    "Is_ListChoice": 1,
                    "Is_Date": 0,
                    "Is_Numeric": 1,
                    "Is_Autocomplete": 0,
                    "Is_Multivalued": 0,
                    "Type": "FOREIGN_TABLE",
                    "Possible_Value": [
                        {"Id": 2, "Label": "Exporté"},
                        {"Id": 1, "Label": "Ok"},
                    ],
                },
                {
                    "Index_Id": "custom_n8",
                    "Label": "Statut de paiement",
                    "Mandatory": False,
                    "Is_ListChoice": 1,
                    "Is_Date": 0,
                    "Is_Numeric": 1,
                    "Is_Autocomplete": 0,
                    "Is_Multivalued": 0,
                    "Type": "FOREIGN_TABLE",
                    "Possible_Value": [{"Id": 1, "Label": "Payé"}],
                },
            ],
            "Rights": {"Can_Upload_Docs": 1, "Can_Search_Docs": 1, "Can_View_Docs": 1},
            "Service": [
                "admin_documents_types",
                "admin_shares",
                "admin_stamps",
                "admin_subscription_usage",
                "admin_users",
                "docs_conversation",
                "export_sepa",
                "view_comments",
                "view_conversations",
                "view_doc_history",
                "view_stamps",
                "view_system_history",
                "visuel_doublons",
                "admin_edit_envoi_groupe",
                "admin_trees",
                "docs_comment",
                "docs_stamp",
                "view_users_list_conversations",
                "view_users_list_diffusion",
                "docs_depot",
                "docs_depot_agent",
                "docs_depot_mail",
                "docs_securibox",
                "docs_edit_doc",
                "edit_doc_folders",
                "create_accounting_files",
                "help_hexapage_documentation",
                "admin_edit_indexes",
                "create_charts",
                "docs_history",
                "docs_print",
                "docs_save",
                "docs_search",
                "docs_view",
                "export_excel",
                "help_documentation",
                "help_supportline",
                "search_advanced_search",
                "search_expert_search",
                "search_save_search",
                "search_saved_searches",
                "search_tree_search",
                "doc_view_original",
                "docs_email_docs",
                "docs_post_docs",
                "docs_publish",
                "admin_edit_saved_queries",
                "lad_autoedit_templates",
                "LAD_Edit_Templates",
                "docs_delete_doc",
            ],
        },
        {
            "Coll_Id": "coll_23",
            "Label": "Classeur Fournisseur | Marius_2",
            "Indexes": [],
            "Index": [
                {
                    "Index_Id": "custom_n3",
                    "Label": "Informations Générales|Type de document",
                    "Mandatory": True,
                    "Is_ListChoice": 1,
                    "Is_Date": 0,
                    "Is_Numeric": 1,
                    "Is_Autocomplete": 0,
                    "Is_Multivalued": 0,
                    "Type": "DOCUMENT_TYPE",
                    "Possible_Value": [
                        {"Id": 13, "Label": "Avoir"},
                        {"Id": 15, "Label": "Bon de commande"},
                        {"Id": 14, "Label": "Bon de livraison"},
                        {"Id": 16, "Label": "Devis"},
                        {"Id": 3, "Label": "Facture"},
                    ],
                },
                {
                    "Index_Id": "custom_t2",
                    "Label": "Informations Générales|Fournisseur",
                    "Mandatory": True,
                    "Is_ListChoice": 0,
                    "Is_Date": 0,
                    "Is_Numeric": 0,
                    "Is_Autocomplete": 1,
                    "Is_Multivalued": 0,
                    "Type": "DESIGNATION_FOURNISSEUR_CHORUS_PRO",
                },
                {
                    "Index_Id": "custom_t3",
                    "Label": "Informations Générales|Référence du document",
                    "Mandatory": True,
                    "Is_ListChoice": 0,
                    "Is_Date": 0,
                    "Is_Numeric": 0,
                    "Is_Autocomplete": 0,
                    "Is_Multivalued": 0,
                    "Type": "NUMERO_FACTURE_CHORUS_PRO",
                },
                {
                    "Index_Id": "custom_d4",
                    "Label": "Informations Générales|Date du document",
                    "Mandatory": True,
                    "Is_ListChoice": 0,
                    "Is_Date": 1,
                    "Is_Numeric": 0,
                    "Is_Autocomplete": 0,
                    "Is_Multivalued": 0,
                    "Type": "DATE_FACTURE_CHORUS_PRO",
                },
                {
                    "Index_Id": "custom_d1",
                    "Label": "Informations Générales|Date d'échéance",
                    "Mandatory": False,
                    "Is_ListChoice": 0,
                    "Is_Date": 1,
                    "Is_Numeric": 0,
                    "Is_Autocomplete": 0,
                    "Is_Multivalued": 0,
                    "Type": "DATE_ECHEANCE",
                },
                {
                    "Index_Id": "custom_f1",
                    "Label": "Informations Générales|Montant HT",
                    "Mandatory": False,
                    "Is_ListChoice": 0,
                    "Is_Date": 0,
                    "Is_Numeric": 1,
                    "Is_Autocomplete": 0,
                    "Is_Multivalued": 0,
                    "Type": "HT",
                },
                {
                    "Index_Id": "custom_f3",
                    "Label": "Informations Générales|Montant TVA",
                    "Mandatory": False,
                    "Is_ListChoice": 0,
                    "Is_Date": 0,
                    "Is_Numeric": 1,
                    "Is_Autocomplete": 0,
                    "Is_Multivalued": 0,
                    "Type": "TVA",
                },
                {
                    "Index_Id": "custom_f2",
                    "Label": "Informations Générales|Montant TTC",
                    "Mandatory": False,
                    "Is_ListChoice": 0,
                    "Is_Date": 0,
                    "Is_Numeric": 1,
                    "Is_Autocomplete": 0,
                    "Is_Multivalued": 0,
                    "Type": "TTC",
                },
                {
                    "Index_Id": "custom_t6",
                    "Label": "Validation|Responsable de validation",
                    "Mandatory": False,
                    "Is_ListChoice": 1,
                    "Is_Date": 0,
                    "Is_Numeric": 0,
                    "Is_Autocomplete": 0,
                    "Is_Multivalued": 0,
                    "Type": "USERS_LIST",
                    "Possible_Value": [
                        {
                            "Id": "74f916c011391ba7ed47caf1e1ce083c",
                            "Label": "GRENOUILLEAU Antonin",
                        },
                        {
                            "Id": "2199661efe186f32a741b9b286070b3f",
                            "Label": "Hivelin Marius",
                        },
                    ],
                },
                {
                    "Index_Id": "custom_t7",
                    "Label": "Validation|Responsable de validation BAP",
                    "Mandatory": False,
                    "Is_ListChoice": 1,
                    "Is_Date": 0,
                    "Is_Numeric": 0,
                    "Is_Autocomplete": 0,
                    "Is_Multivalued": 0,
                    "Type": "USERS_LIST",
                    "Possible_Value": [
                        {
                            "Id": "3e9ad4345be1b5f6e721d06d7729d39d",
                            "Label": "Alexandre BAUDON",
                        },
                        {
                            "Id": "74f916c011391ba7ed47caf1e1ce083c",
                            "Label": "Antonin GRENOUILLEAU",
                        },
                        {
                            "Id": "3a04a02e0a0f419b241ffc12e65028fa",
                            "Label": "Arnaud DELASTRE",
                        },
                        {
                            "Id": "a1c7a2fc949869d9bd625ac099e7bd9c",
                            "Label": "Audrey MAS",
                        },
                        {
                            "Id": "e2afc39b8813fc3c4f30a2dccec1adf3",
                            "Label": "Fleur CIANTELLI",
                        },
                        {
                            "Id": "710bca52a37973418e783f7fefde58f5",
                            "Label": "Formulaire Jotform",
                        },
                        {
                            "Id": "e88bef785b5a8c9c8ce8212ea94c2226",
                            "Label": "Germain MALICZAK",
                        },
                        {
                            "Id": "e69645dbaa97bcbb9e5fa62246eddd7c",
                            "Label": "Guillaume GRIMAUD",
                        },
                        {
                            "Id": "b629639e175bc740e092f0923de5e5ab",
                            "Label": "Julien CASTAING",
                        },
                        {
                            "Id": "182a9f1ff961e5acffc5dc52636734ad",
                            "Label": "Ludovic TONDU",
                        },
                        {
                            "Id": "2199661efe186f32a741b9b286070b3f",
                            "Label": "Marius Hivelin",
                        },
                        {
                            "Id": "a2f35187c8bb508f1f2fd002ac2c5282",
                            "Label": "Marius Hivelin",
                        },
                        {
                            "Id": "ef8d29f5361c2b7c12a25511436bbc02",
                            "Label": "Mickaël JOLLYS",
                        },
                        {
                            "Id": "76cc5e409d20c8e7667f902fb9a13eaa",
                            "Label": "Nicolas SCAGLIOLA",
                        },
                        {
                            "Id": "a0f2166611fa922b2e9698c6b3ab7c9e",
                            "Label": "Oscar WOLLMANN",
                        },
                        {
                            "Id": "df9e0cf700d9e6d8fb2a883ca164c5f1",
                            "Label": "Recette Z+ DELTIC DEMO",
                        },
                    ],
                },
                {
                    "Index_Id": "custom_n6",
                    "Label": "Comptabilité|Code journal",
                    "Mandatory": False,
                    "Is_ListChoice": 1,
                    "Is_Date": 0,
                    "Is_Numeric": 1,
                    "Is_Autocomplete": 0,
                    "Is_Multivalued": 0,
                    "Type": "FOREIGN_TABLE",
                    "Possible_Value": [{"Id": 1, "Label": "AC - Achats"}],
                },
                {
                    "Index_Id": "custom_n4",
                    "Label": "Comptabilité|Compte Fournisseur",
                    "Mandatory": False,
                    "Is_ListChoice": 1,
                    "Is_Date": 0,
                    "Is_Numeric": 1,
                    "Is_Autocomplete": 0,
                    "Is_Multivalued": 0,
                    "Type": "FOREIGN_TABLE",
                    "Possible_Value": [
                        {"Id": 9, "Label": "401FOURN - NOM DU FOURNISSEUR"}
                    ],
                },
                {
                    "Index_Id": "custom_n1",
                    "Label": "Comptabilité|Imputation HT",
                    "Mandatory": False,
                    "Is_ListChoice": 1,
                    "Is_Date": 0,
                    "Is_Numeric": 1,
                    "Is_Autocomplete": 0,
                    "Is_Multivalued": 1,
                    "Type": "VENTILATION_HT",
                    "Possible_Value_CreditDebit": [
                        {"Nom_Groupe": "CREDIT", "Id_Father": 1},
                        {
                            "Nom_Groupe": "DEBIT",
                            "Id_Father": -1,
                            "Membre_Groupe": [
                                {"Id": 650, "Label": "6251000 - COMPTE DE TEST"}
                            ],
                        },
                    ],
                    "Is_Son": 1,
                    "Father": "",
                    "Possible_Value": [
                        {
                            "Nom_Groupe": "-1",
                            "Id_Father": -1,
                            "Membre_Groupe": [
                                {"Id": 650, "Label": "6251000 - COMPTE DE TEST"}
                            ],
                        }
                    ],
                },
                {
                    "Index_Id": "custom_n5",
                    "Label": "Comptabilité|Imputation TVA",
                    "Mandatory": False,
                    "Is_ListChoice": 1,
                    "Is_Date": 0,
                    "Is_Numeric": 1,
                    "Is_Autocomplete": 0,
                    "Is_Multivalued": 1,
                    "Type": "VENTILATION_TVA",
                    "Possible_Value_CreditDebit": [
                        {"Nom_Groupe": "CREDIT", "Id_Father": 1},
                        {
                            "Nom_Groupe": "DEBIT",
                            "Id_Father": -1,
                            "Membre_Groupe": [
                                {"Id": 17, "Label": "44560000 - COMPTE DE TEST"}
                            ],
                        },
                    ],
                    "Is_Son": 1,
                    "Father": "",
                    "Possible_Value": [
                        {
                            "Nom_Groupe": "-1",
                            "Id_Father": -1,
                            "Membre_Groupe": [
                                {"Id": 17, "Label": "44560000 - COMPTE DE TEST"}
                            ],
                        }
                    ],
                },
                {
                    "Index_Id": "custom_t5",
                    "Label": "Comptabilité|Complément libellé",
                    "Mandatory": False,
                    "Is_ListChoice": 0,
                    "Is_Date": 0,
                    "Is_Numeric": 0,
                    "Is_Autocomplete": 0,
                    "Is_Multivalued": 0,
                    "Type": "TEXT",
                },
                {
                    "Index_Id": "custom_n2",
                    "Label": "Comptabilité|Mode de règlement",
                    "Mandatory": False,
                    "Is_ListChoice": 1,
                    "Is_Date": 0,
                    "Is_Numeric": 1,
                    "Is_Autocomplete": 0,
                    "Is_Multivalued": 0,
                    "Type": "FOREIGN_TABLE",
                    "Possible_Value": [
                        {"Id": 1, "Label": "CB - Carte Bleue"},
                        {"Id": 3, "Label": "CHQ - Chèque"},
                        {"Id": 2, "Label": "VIR - Virement"},
                    ],
                },
                {
                    "Index_Id": "custom_t4",
                    "Label": "Comptabilité|Numéro de pièce comptable (auto)",
                    "Mandatory": False,
                    "Is_ListChoice": 0,
                    "Is_Date": 0,
                    "Is_Numeric": 0,
                    "Is_Autocomplete": 0,
                    "Is_Multivalued": 0,
                    "Type": "TEXT",
                },
                {
                    "Index_Id": "custom_t1",
                    "Label": "Comptabilité|Exporté (auto)",
                    "Mandatory": False,
                    "Is_ListChoice": 0,
                    "Is_Date": 0,
                    "Is_Numeric": 0,
                    "Is_Autocomplete": 0,
                    "Is_Multivalued": 0,
                    "Type": "TEXT",
                },
                {
                    "Index_Id": "custom_n15",
                    "Label": "BAP",
                    "Mandatory": False,
                    "Is_ListChoice": 1,
                    "Is_Date": 0,
                    "Is_Numeric": 1,
                    "Is_Autocomplete": 0,
                    "Is_Multivalued": 0,
                    "Type": "FOREIGN_TABLE",
                    "Possible_Value": [
                        {"Id": 2, "Label": "Exporté"},
                        {"Id": 1, "Label": "Ok"},
                    ],
                },
                {
                    "Index_Id": "custom_n7",
                    "Label": "Statut de paiement",
                    "Mandatory": False,
                    "Is_ListChoice": 1,
                    "Is_Date": 0,
                    "Is_Numeric": 1,
                    "Is_Autocomplete": 0,
                    "Is_Multivalued": 0,
                    "Type": "FOREIGN_TABLE",
                    "Possible_Value": [{"Id": 1, "Label": "Payé"}],
                },
            ],
            "Rights": {"Can_Upload_Docs": 1, "Can_Search_Docs": 1, "Can_View_Docs": 1},
            "Service": [
                "admin_documents_types",
                "admin_shares",
                "admin_stamps",
                "admin_subscription_usage",
                "admin_users",
                "docs_conversation",
                "export_sepa",
                "view_comments",
                "view_conversations",
                "view_doc_history",
                "view_stamps",
                "view_system_history",
                "visuel_doublons",
                "admin_edit_envoi_groupe",
                "admin_trees",
                "docs_comment",
                "docs_stamp",
                "view_users_list_conversations",
                "view_users_list_diffusion",
                "docs_depot",
                "docs_depot_agent",
                "docs_depot_mail",
                "docs_securibox",
                "docs_edit_doc",
                "edit_doc_folders",
                "create_accounting_files",
                "help_hexapage_documentation",
                "admin_edit_indexes",
                "create_charts",
                "docs_history",
                "docs_print",
                "docs_save",
                "docs_search",
                "docs_view",
                "export_excel",
                "help_documentation",
                "help_supportline",
                "search_advanced_search",
                "search_expert_search",
                "search_save_search",
                "search_saved_searches",
                "search_tree_search",
                "doc_view_original",
                "docs_email_docs",
                "docs_post_docs",
                "docs_publish",
                "admin_edit_saved_queries",
                "lad_autoedit_templates",
                "LAD_Edit_Templates",
                "docs_delete_doc",
            ],
        },
        {
            "Coll_Id": "",
            "Label": "_SERVICE_RECHERCHE_MULTI_CLASSEUR_LABEL",
            "Indexes": [],
            "Rights": {"Can_Upload_Docs": 0, "Can_Search_Docs": 1, "Can_View_Docs": 0},
            "Service": [
                "docs_search",
                "search_advanced_search",
                "search_expert_search",
                "search_save_search",
                "search_saved_searches",
                "search_tree_search",
            ],
        },
    ],
}
